Update push.yml

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -36,7 +36,7 @@ jobs:
         with:
           node-version: ${{ env.NODE_VERSION }}
       - name: Install tools
-        run: npm install markdown-table-formatter -g; gem install mdl
+        run: npm install markdown-table-formatter -g; gem install --user-install mdl
       - name: Lint
         run: markdown-table-formatter **/*.md; mdl -r~MD013,~MD009,~MD002,~MD033 README.md ./docs ./i18n
   translations:
@@ -58,9 +58,9 @@ jobs:
       - name: Test no changes
         run: |
           if [ -z "$(git status --short)" ]; then
-            echo "Translations up to date"; exit 1
+            echo "::debug::Translations up to date :clap::clap::clap:"; exit 0
           else
-            echo "Translations missing"; exit 0
+            echo "::error title={Translations missing}::"; exit 1
           fi
 
 
